# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subcategory',
            field=models.ManyToManyField(to='category.Subcategory'),
        ),
    ]
