# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20160519_1634'),
        ('account', '0004_extuser_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.City'),
            preserve_default=False,
        ),
    ]
